
//example of var,const,let


const accountId=12345
let   accountEmail="mantu088@gmail.com"        
var   accountPassword="12345"                //prefer it is not use because issue in block scope and functional scope...
accountCity ="Jaipur"                       //a variable may define like this it mins define without varabletype that is not prafreble
let accoutState;                            //a variable can be define like this  withourt any value that is initilly undefined whenever any value is not initelize to it

// accountId=565656                          //constant may not be modified it remain same
accountEmail="mantukumar87586299@gmail.com"  //variable (var and let) may chenge .. 
accountPassword="112233"
accountCity="bangleru"

console.log(accountEmail);

console.table([accountId,accountEmail,accountPassword,accountCity,accoutState]); 

  
  